### ISSUE TITLE
Reference to a local (non-exported) symbol 'CoolHttpModule'

### ISSUE THREAD

**Issue by bymeftun** [Hacklone/angular2-cool-http#11]
Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'CoolHttpModule'. Consider exporting the symbol (position 16:14 in the original .ts file)

**Comment by Hacklone** [comment]
Hey,

Thanks for reporting.

- Which version of the package are you using?
- Which version of angular are you using?
- Which version of compiler-cli are you using?

Thanks,
Barna

**Comment by bymeftun** [comment]
cli: 1.0.1
compiler-cli: 4.1.0
Angular 2+
npm v3.10.10
node v6.10.3

thanks

**Comment by Hacklone** [comment]
I cannot reproduce with the following versions:

```
- angular2-cool-http@2.2.0
- @angular/cli@1.0.3
- @angular/compiler@4.1.3
- @angular/compiler-cli@4.1.3
- @angular/core@4.1.3
- @angular/http@4.1.3
```

**Comment by Hacklone** [comment]
Found some problems with peerDependency versions. Just published version 2.2.1. Did that help?

**Comment by bymeftun** [comment]
Yes, the issue is fixed

**Comment by Hacklone** [comment]
Thanks
