### ISSUE TITLE
Error building CLI Project

### ISSUE THREAD

**Issue by harryhahn** [Hacklone/angular2-cool-http#9]
After import the CollHttpModule i can't build my angular-cli (rc0) project. 
A Error occur:

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/node_module
s/@angular/core/src/metadata.d.ts, resolving symbol NgModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/node_modules/@angular/core/index.d.ts, resolving symbol CoolHttpModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/index.d.ts, resolving symbol CoolHttpModule in C:/Entwicklung/Projekte/marenta/marenta/node_modules/angular2-cool-http/index.d.ts
`

**Comment by Hacklone** [comment]
Hey,

This should be fixed by the latest version.
Please delete the node_modules/angular2-cool-http folder then ```npm i```
 
Could you check it?

Thanks,
Barna

**Comment by harryhahn** [comment]
Great it works, after update the project package.json .
thanks
